### ISSUE TITLE
Image permissions

### ISSUE THREAD

**Issue by jon6fingrs** [strobi/docker-rpi-syncthing#1]
Hi, thanks for the docker image. Just to let you know, not sure if I had done anything wrong or not, but after loading your docker container, I was able to access the syncthing webpage but kept getting errors that syncthing could not write files or make directories. I ended up fixing it by making a new user called "syncthing" and adding it to the same group as my normal raspberry pi account. Am a newb so not sure if I did anything wrong in creating the container or not though.

**Comment by strobh** [comment]
Hi, thanks for your feedback. Did you build the container on your own or did you use the prebuilt container on Docker Hub?

I can think of two different causes:
1. The two volumes mounted from the host into the container (`~/syncthing/config` and `~/syncthing/data`) did not exist on the host and were created by docker (but then owned by root)
2. The two volumes did exist but were not owned by the user with the uid 1000 (default user `pi` on most operating systems for the Pi).

I clarified both aspects in the README file now.

**Comment by jon6fingrs** [comment]
So now that I’m looking at portainer, looks like it used a UID 1001 and GID 1001. Maybe I typed it in incorrectly because I just checked and you’re right, both of those on my pi are 1000. Thanks!
